routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LibraryController;
use App\Http\Controllers\CategoryController;
// use App\Http\Controllers\CarouselController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\RequestBookController;
use App\Http\Controllers\ApprovedBookController;
use App\Http\Controllers\IssueBookController;
use App\Http\Controllers\ReturnBookController;
use App\Http\Controllers\ReissueBookController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\ContactUsController;
use App\Http\Controllers\AboutUsController;
use App\Http\Controllers\AwardController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EducationController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\MembershipController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PublicationController;
use App\Http\Controllers\ResearchSupervisionController;
use App\Http\Controllers\TeachingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend/home');
})->name('homepage');

require __DIR__.'/auth.php';
// frontend all route
Route::middleware('auth')->controller(LibraryController::class)->group(function(){
    Route::get('/library-dashboard','index')->name('library-dashboard');
    Route::get('/get-book','booklist')->name('get-book');
    Route::get('/teacher-list','teacherlist')->name('teacher-list');
    Route::get('/teacher-details/{id}','teacherDetails')->name('teacher-details');
    Route::get('/student-list','studentlist')->name('student-list');
    Route::post('/book/request','request_store')->name('book.request');
    Route::get('/request-cancel/{id}/{book_id}','destroy')->name('request.destroy');
    Route::get('/user-reissue/{id}','reissue')->name('user.reissue');
});

Route::middleware('auth')->controller(ContactUsController::class)->group(function(){
  Route::get('/user/contactus','index')->name('user.contactus.index');
  Route::post('/contactus','store')->name('user.contactus.store');
});

Route::controller(AboutUsController::class)->group(function(){
  Route::get('/user/aboutus','index')->name('user.aboutus.index');
});

Route::controller(EventController::class)->group(function(){
  Route::get('/user/event','index')->name('user.event.index');
});

//Teacher Profile Info

Route::middleware('auth')->group(function() {
  Route::middleware(['role:teacher'])->group(function() {
    Route::resource('research-supervisions', ResearchSupervisionController::class);
    Route::resource('teachings', TeachingController::class);
    Route::resource('educations', EducationController::class);
    Route::resource('publications', PublicationController::class);
    Route::resource('awards', AwardController::class);
    Route::resource('memberships', MembershipController::class);
  });

  Route::controller(ProfileController::class)->group(function(){
    Route::get('/user/profile','index')->name('user.profile.index');
    Route::patch('/user/profile','updateProfile')->name('user.profile.update');
    Route::patch('/change/password','changePassword')->name('user.change.password');
  });
});

Route::middleware(['auth', 'role:admin'])->group(function() {
  Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
  
  Route::resource('teachers', TeacherController::class);
  Route::resource('students', StudentController::class);

  Route::resource('categories', CategoryController::class);
  Route::resource('books', BookController::class);
//  Route::resource('carousels', CarouselController::class)->middleware(['auth','role']);
  
  Route::get('/admin-profile',[ProfileController::class, 'adminIndex'])->name('admin.profile.index');
  
  Route::get('/reissuebooks',[ReissueBookController::class, 'index'])->name('reissue.book.index');
  Route::get('/reissuebooks/{id}',[ReissueBookController::class, 'reissue'])->name('reissue.book.reissue');

  Route::get('/returnbooks',[ReturnBookController::class, 'index'])->name('return.book.index');

  Route::get('/issuebooks',[IssueBookController::class, 'index'])->name('issue.book.index');
  Route::get('/issuebooks/{id}/{book_id}',[IssueBookController::class, 'return'])->name('issue.book.return');

  Route::get('/approvedbooks',[ApprovedBookController::class, 'index'])->name('approved.book.index');
  Route::get('/approvedbooks/{id}',[ApprovedBookController::class, 'issue'])->name('approved.book.issue');

  Route::get('/requestbooks',[RequestBookController::class, 'index'])->name('request.book.index');
  Route::get('/requestbooks/{id}/{book_id}',[RequestBookController::class, 'approved'])->name('request.book.approved');

});
//end manage book library request and status change of admin

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\Category;
use App\Http\Requests\BookRequest;
use Illuminate\Http\Request;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();


        $books = Product::latest()->paginate(6);
        return view('admin.book.index', compact('books', 'categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('backend.products.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BookRequest $request)
    {


        if ($file = $request->file('bookimage')) {
            $filename = date('dmY') . time() . '.' . $file->getClientOriginalExtension();
            $file->move(storage_path('app/public/books'), $filename);
        }

        Product::create(
            [
                'booktitle' => $request->booktitle,
                'bookauthor' => $request->bookauthor,
                'bookedition' => $request->bookedition,
                'bookquantity' => $request->bookquantity,
                'status' => $request->is_active ?? false,
                'bookimage' => $filename ?? '',
                'category_id' => $request->category,
            ]
        );
        return redirect()->route('books.index')->withMessage('New book successfully added')->withType('success');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        $productshow = Product::findOrFail($id);
        return view('backend.products.show', compact('productshow'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = Product::findOrFail($id);
        $categories = Category::all();

        return view('admin.book.edit', compact('book', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $filename = null;
        if ($file = $request->file('bookimage')) {
            $filename = date('dmY') . time() . '.' . $file->getClientOriginalExtension();
            $file->move(storage_path('app/public/books'), $filename);
        }
        $productupdate = Product::findOrFail($id);
        $data = [
            'booktitle' => $request->booktitle,
            'bookauthor' => $request->bookauthor,
            'bookedition' => $request->bookedition,
            'bookquantity' => $request->bookquantity,
            'price' => $request->price,
            'status' => $request->is_active ?? false,
            'category_id' => $request->category ?? '2',
        ];

        if ($filename) {
            $data['bookimage'] = $filename;
        }

        // dd($data);

        $productupdate->update($data);
        return redirect()->route('books.index')->withMessage('Successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            Product::findOrFail($id)->delete();
        } catch (\Exception $ex) {
            return redirect()->route('books.index')->withMessage('Can not remove book. Book is already collected by someone.');
        }
        return redirect()->route('books.index')->withMessage('Successfully deleted');
    }
}

resources/views/admin/book/edit.blade.php
<x-backend.layout.master>
    @slot('title')
    Book Update
    @endslot
    <main id="main" class="main">
        <div class="card mb-4 mt-4 ">
            <div class="card-header ">
                <i class="fas fa-table me-1"></i>
                Book Update
                <a href="{{ route('books.index') }}"> <button class=" btn-sm btn btn-outline-primary"><i
                            class="fa-solid fa-backward"></i></button></a>
            </div>

            <div class=" card w-75 mx-auto mt-4 mb-4" style="background-color: #f3fcf2">
                <div class="card-header text-center shadow-sm" style="background-color: #58ed85">
                    <h4> <b> Book Update</b></h4>
                </div>
                <form class="row g-3" role="form" action="{{ route('books.update', $book->id) }}" method="post"
                    enctype="multipart/form-data">
                    @csrf
                    @method('patch')


                    <x-backend.alertmessage.alertmessage type="success" />

                    <select name="category" id="" class="form-select" aria-label="Default select example">
                        <option value="">Select Category</option>
                        @foreach ($categories as $category)
                        <option value="{{ $category->id }}">{{ $category->title }}</option>
                        @endforeach
                    </select>

                    <div class="col-md-6">
                        <x-frontend.form.input name="booktitle" text="Book Tile" type="text"
                            :value="old('booktitle', $book->booktitle)" />
                    </div>
                    <div class="col-md-6">
                        <x-frontend.form.input name="bookauthor" text="Book Author" type="text"
                            :value="old('bookauthor', $book->bookauthor)" />
                    </div>
                    <div class="col-md-6">
                        <x-frontend.form.input name="bookedition" text="Book Edition" type="text"
                            :value="old('bookedition', $book->bookedition)" />
                    </div>
                    <div class="col-md-6">
                        <x-frontend.form.input name="bookquantity" text="Book Quantity" type="number"
                            :value="old('bookquantity', $book->bookquantity )" />
                    </div>


                    <div class="col-md-12">
                        <x-frontend.form.input name="bookimage" text="Book Image" type="file" />
                    </div>

                    <div class="form-check">
                        <input name="is_active" class="form-check-input" type="checkbox" value="1" id="isActiveInput"
                            checked>
                        <label class="form-check-label" for="isActiveInput">
                            Is Active
                        </label>
                    </div>

                    <div class="card-footer bg-white">
                        <div class="d-grid gap-2 col-6 mx-auto d-flex">
                            <button type="submit" class="btn btn-success w-50 btn-sm" type="button">Save <i
                                    class="fa-solid fa-paper-plane"></i></button>
                            <a href="{{ route('books.index') }}"><button class="btn btn-danger btn-sm"
                                    type="button">Cancel</button></a>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </main>
</x-backend.layout.master>

resources/views/admin/book/index.blade.php
<x-backend.layout.master>

      @slot('title')
    all-book
    @endslot
 <main id="main" class="main">

    <div class="pagetitle">
      <h1>Book List</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
          <li class="breadcrumb-item active">BookList</li>
        </ol>
        <button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#BookModal">
  Add Book
</button>
      </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
         <x-backend.alertmessage.alertmessage type="success"/>
<table class="table table-bordered border-primary">
   <thead>
                <tr>
                    <th>SL No</th>
                    <th>Book Title</th>
                    <th>Book Author</th>
                    <th>Book Edition</th>
                    <th>Book Quantity</th>
                    <th>Category</th>
                    <th>Image</th>
                    <th>Status</th>
                    <th>Created Data</th>
                    <th>Action</th>
                </tr>
            </thead>
             <tbody>
                @foreach ($books as $book)
                    
               
               <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $book->booktitle }}</td>
                    <td>{{ $book->bookauthor }}</td>
                    <td>{{ $book->bookedition }}</td>
                    <td>{{ $book->bookquantity }}</td>
                    <td>{{ $book->categories->title }}</td>
                    <td class="text-center"><img src="{{ asset('storage/books').'/'.$book->bookimage }}" alt="hhh" class="img-fluid" style="width:100px;height:100px"></td>
                    <td>{{ $book->status?'Active':'In Active' }}</td>
                    <td>{{ $book->created_at }}</td>
                     
                    

                    
                    <td>
                        <div class="d-flex ">
                            <x-backend.buttonlink.viewlink  action="{{ route('books.show',['book'=>$book->id ])}}"/>
                            <x-backend.buttonlink.editlink action="{{ route('books.edit',['book'=>$book->id ])}}"/>
                            <x-backend.buttonlink.deletelink action="{{ route('books.destroy',['book'=>$book->id ])}}"/>
                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
</table>

<div>
  {{$books->links()}}
</div>

      
       
    </section>

  </main><!-- End #main -->







 
<div class="modal fade" id="BookModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header bg-primary text-white center">
           Add New Book
          <button type="button" class="btn-close btn-white" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
             <form class="row g-3" role="form" action="{{ route('books.store') }}" method="post" enctype="multipart/form-data">
                @csrf
              
                 
                 <br>
                

                 <x-backend.alertmessage.alertmessage type="success"/> 
                
                <select name="category" id="" class="form-select" aria-label="Default select example">
                    <option value="">Select Category</option>
                    @foreach ($categories as $category)
                    <option value="{{ $category->id }}">{{ $category->title }}</option>
                    @endforeach
                </select>
               
                <div class="col-md-6">
                    <x-frontend.form.input name="booktitle" text="Book Tile" type="text" :value="old('booktitle')" />
               </div>
                <div class="col-md-6">
                    <x-frontend.form.input name="bookauthor" text="Book Author" type="text" :value="old('bookauthor')" />
               </div>
                <div class="col-md-6">
                    <x-frontend.form.input name="bookedition" text="Book Edition" type="text" :value="old('bookedition')" />
               </div>
                <div class="col-md-6">
                    <x-frontend.form.input name="bookquantity" text="Book Quantity" type="number" :value="old('bookquantity')" />
               </div>
              
                
                  <div class="col-md-12">
                    <x-frontend.form.input name="bookimage" text="Book Image" type="file"/>
                  </div>
                  
               <div class="form-check">
                <input name="is_active" class="form-check-input" type="checkbox" value="1" id="isActiveInput" checked>
                <label class="form-check-label" for="isActiveInput">
                    Is Active
                </label>
            </div>
                
    
                  
             <div class="card-footer bg-white">
                <div class="d-grid gap-2 col-6 mx-auto d-flex">
                    <button type="submit" class="btn btn-success w-50 btn-sm" type="button">Save <i class="fa-solid fa-paper-plane"></i></button>
                     <a href="{{ route('books.index') }}"><button class="btn btn-danger btn-sm" type="button">Cancel</button></a>
                  </div>
          </div> 
        </form> 
      </div>
    </div>
  </div>
  {{-- <script>
    $.ajaxSetup({
    headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
});
  </script>
  <script>
    $(document).ready(function(){
        $(document).on('click','.add_category',function(e){
            e.preventDefualt();
            let title=$('#title').val();
            let description=$('#description').val();
            console.log(title+description);
        })
    })
  </script> --}}
</x-backend.layout.master>

resources/views/admin/book/reissue.blade.php
<x-backend.layout.master>
    @slot('title')
   ReIssue
    @endslot
<div class="card mb-4 mt-3">
    <div class="card-header" style="background-color: #defffe">
        <i class="fas fa-table me-1"></i>
      Reissue
       <a href="{{ route('sellbooks.create') }}"> <button class="btn btn-outline-info btn-sm text-black">Add Request for Donate</button></a>
    </div>
   <x-backend.alertmessage.alertmessage type="success"/>
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>SL No</th>
                    <th>Book Title</th>
                    <th>Book Author</th>
                    <th>Book Edition</th>
                    <th>Book Quantity</th>
                    <th>Approved Id</th>
                    <th>Fine</th>
                    <th>Return Date</th>
                    <th>Applicant</th>
                    <th>ACTION</th>
                </tr>
            </thead>

            <tbody>
                @foreach ($getdonate as $sellbook)

                @if ($sellbook->status=='reissue')
                <tr>
                  <td>{{ $loop->iteration }}</td>
                
                  <td>{{ $sellbook->product->booktitle }}</td>
                  <td>{{ $sellbook->product->bookauthor }}</td>
                  <td>{{ $sellbook->product->bookedition }}</td>
                  <td>{{ $sellbook->product->bookquantity }}</td>
                  <td>{{ $sellbook->approved_id }}</td>
                  <td>0</td>
                  <td>{{ $sellbook->return_date }}</td>
                  <td><button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal">
                      Applicant Inormation
                    </button></td>
                   
                  <td class="d-flex">
                   
                    <a href="{{ route('issue.update',['id'=>$sellbook->id]) }}" class="btn btn-primary btn-sm">Reissue</a>
                   
                 
                    
                     <a href="{{ route('reissue.cancel',['id'=>$sellbook->id]) }}" class="btn btn-danger btn-sm">Cancel</a>
                    
                  </td>
              </tr>
                @endif 
              
                @endforeach
            </tbody>
        </table>

    </div>
</div>


<!-- Button trigger modal -->
 
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>


</x-backend.layout.master>

resources/views/admin/book/request.blade.php
<x-backend.layout.master>
    @slot('title')
    Add Book
    @endslot
<div class="card mb-4 mt-3">
    <div class="card-header" style="background-color: #defffe">
        <i class="fas fa-table me-1"></i>
        Add Book
       <a href="{{ route('book.create') }}"> <button class="btn btn-outline-info btn-sm text-black">Add Request for Donate</button></a>
    </div>
   <x-backend.alertmessage.alertmessage type="success"/>
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>SL No</th>
                    <th>Book Title</th>
                    <th>Book Author</th>
                    <th>Book Edition</th>
                    <th>Approved Id</th>
                    <th>Fine</th>
                    <th>Applicant</th>
                    <th>ACTION</th>
                </tr>
            </thead>

            <tbody>
                @foreach ($getdonate as $sellbook)


                <tr>
                    <td>{{ $loop->iteration }}</td>
                  
                    <td>{{ $sellbook->product->booktitle }}</td>
                    <td>{{ $sellbook->product->bookauthor }}</td>
                    <td>{{ $sellbook->product->bookedition }}</td>
                    <td>{{ $sellbook->product->bookquantity }}</td>
                    <td>{{ $sellbook->approved_id }}</td>
                    <td>0</td>
                    <td><button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        Applicant Inormation
                      </button></td>
                     
                    <td class="d-flex">
                        <div class="d-flex justify-content-between">
                            <form class="row g-3" role="form" action="{{ route('getdonates.update',['getdonate'=>$sellbook->id, 'id'=>$sellbook->product->id]) }}" method="post" enctype="multipart/form-data">

                                @csrf
                                @method('patch')
                                {{-- <input name="bookquantity" type="hidden" text="" value="{{$sellbook->product->bookquantity}}"/>
                                <input name="bookid" type="hidden" text="" value="{{$sellbook->product->bookid}}"/> --}}
                                  @if ($sellbook->status=="approved")
                                  <a href="{{ route('issue.update',['id'=>$sellbook->id]) }}" class="btn btn-success btn-sm">Issue</a>
                                  
                                  </button>
                                   @elseif ($sellbook->status=="cancel")
                                   <button type="submit" class="btn btn-danger btn-sm disabled" type="button">
                                    Cancel
                                  </button>
                                   @elseif ($sellbook->status=="issue" || $sellbook->status=="reissue")
                                   <a href="{{ route('return.update',['id'=>$sellbook->id,'bookid'=>$sellbook->product->id]) }}" class="btn btn-info btn-sm">Return</a>
                                   
                                   @elseif ($sellbook->status=="return")
                                    <button class="btn btn-success btn-sm disabled">Returned</button>
                                  @else
                                  <button type="submit" class="btn btn-success btn-sm disabl" type="button">
                                    Pending
                                  </button>
                                 
                                  @endif
                                 
                               
                            </form>
                     @if (!$sellbook->status=="cancel"||$sellbook->status=="approved")
                     <a href="{{ route('getdonates.destroy',['id'=>$sellbook->id, 'bookid'=>$sellbook->product->id]) }}" class="btn btn-danger btn-sm ml-2">Cancel</a> 
                     @endif
                            
                        </div>
                      
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

    </div>
</div>


<!-- Button trigger modal -->
 
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>


</x-backend.layout.master>

resources/views/admin/book/show.blade.php
 
    <x-backend.layout.master>
        @slot('title')
        Sell Book Details
        @endslot
    <div class="card mb-4 mt-4">
       
        <div class="card-header ">
            <i class="fas fa-table me-1"></i>
            Sell Book Details
           <a href="{{ route('sellbooks.index') }}"> <button class=" btn-sm btn btn-outline-primary"><i class="fa-solid fa-backward"></i></button></a>
        </div>
      
        <div class="card w-75 mx-auto mt-4 mb-4" style="background-color: #f3fcf2">
            <div class="card-header text-center shadow-sm" style="background-color: #58ed85">
             <h4> <b> Sell Book Details</b></h4>
            </div>
            <td><img src="{{asset('/storage/sellbooks/'.$sellbookshow->bookimage)}}" alt="" style="width:400px;height:200px" class="mx-auto m-2"></td>
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th> Book Title </th>
                  <td>{{ $sellbookshow->booktitle }}</td>
                 
                </tr>
                <tr>
                  <th> Book Author</th>
                  <td>{{ $sellbookshow->bookauthor }}</td>
                 
                </tr>
                <tr>
                  <th> Book Edition</th>
                  <td>{{ $sellbookshow->bookedition }}</td>
                 
                </tr>
                <tr>
                  <th> Book Price</th>
                  <td>{{ $sellbookshow->price }}</td>
                 
                </tr>
                <tr>
                  <th> Mobile</th>
                  <td>{{ $sellbookshow->mobile }}</td>
                 
                </tr>
                
              </thead>
              <tbody>
              </tbody>
            </table>

          <div class="cart-footer bg-info">
          
          </div>
          </div>
    </div>
     
    </x-backend.layout.master>
 
 
 