routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LibraryController;
use App\Http\Controllers\CategoryController;
// use App\Http\Controllers\CarouselController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\RequestBookController;
use App\Http\Controllers\ApprovedBookController;
use App\Http\Controllers\IssueBookController;
use App\Http\Controllers\ReturnBookController;
use App\Http\Controllers\ReissueBookController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\ContactUsController;
use App\Http\Controllers\AboutUsController;
use App\Http\Controllers\AwardController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EducationController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\MembershipController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PublicationController;
use App\Http\Controllers\ResearchSupervisionController;
use App\Http\Controllers\TeachingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend/home');
})->name('homepage');

require __DIR__.'/auth.php';
// frontend all route
Route::middleware('auth')->controller(LibraryController::class)->group(function(){
    Route::get('/library-dashboard','index')->name('library-dashboard');
    Route::get('/get-book','booklist')->name('get-book');
    Route::get('/teacher-list','teacherlist')->name('teacher-list');
    Route::get('/teacher-details/{id}','teacherDetails')->name('teacher-details');
    Route::get('/student-list','studentlist')->name('student-list');
    Route::post('/book/request','request_store')->name('book.request');
    Route::get('/request-cancel/{id}/{book_id}','destroy')->name('request.destroy');
    Route::get('/user-reissue/{id}','reissue')->name('user.reissue');
});

Route::middleware('auth')->controller(ContactUsController::class)->group(function(){
  Route::get('/user/contactus','index')->name('user.contactus.index');
  Route::post('/contactus','store')->name('user.contactus.store');
});

Route::controller(AboutUsController::class)->group(function(){
  Route::get('/user/aboutus','index')->name('user.aboutus.index');
});

Route::controller(EventController::class)->group(function(){
  Route::get('/user/event','index')->name('user.event.index');
});

//Teacher Profile Info

Route::middleware('auth')->group(function() {
  Route::middleware(['role:teacher'])->group(function() {
    Route::resource('research-supervisions', ResearchSupervisionController::class);
    Route::resource('teachings', TeachingController::class);
    Route::resource('educations', EducationController::class);
    Route::resource('publications', PublicationController::class);
    Route::resource('awards', AwardController::class);
    Route::resource('memberships', MembershipController::class);
  });

  Route::controller(ProfileController::class)->group(function(){
    Route::get('/user/profile','index')->name('user.profile.index');
    Route::patch('/user/profile','updateProfile')->name('user.profile.update');
    Route::patch('/change/password','changePassword')->name('user.change.password');
  });
});

Route::middleware(['auth', 'role:admin'])->group(function() {
  Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
  
  Route::resource('teachers', TeacherController::class);
  Route::resource('students', StudentController::class);

  Route::resource('categories', CategoryController::class);
  Route::resource('books', BookController::class);
//  Route::resource('carousels', CarouselController::class)->middleware(['auth','role']);
  
  Route::get('/admin-profile',[ProfileController::class, 'adminIndex'])->name('admin.profile.index');
  
  Route::get('/reissuebooks',[ReissueBookController::class, 'index'])->name('reissue.book.index');
  Route::get('/reissuebooks/{id}',[ReissueBookController::class, 'reissue'])->name('reissue.book.reissue');

  Route::get('/returnbooks',[ReturnBookController::class, 'index'])->name('return.book.index');

  Route::get('/issuebooks',[IssueBookController::class, 'index'])->name('issue.book.index');
  Route::get('/issuebooks/{id}/{book_id}',[IssueBookController::class, 'return'])->name('issue.book.return');

  Route::get('/approvedbooks',[ApprovedBookController::class, 'index'])->name('approved.book.index');
  Route::get('/approvedbooks/{id}',[ApprovedBookController::class, 'issue'])->name('approved.book.issue');

  Route::get('/requestbooks',[RequestBookController::class, 'index'])->name('request.book.index');
  Route::get('/requestbooks/{id}/{book_id}',[RequestBookController::class, 'approved'])->name('request.book.approved');

});
//end manage book library request and status change of admin

app/Models/Education.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Education extends Model
{
    // use HasFactory;
    protected $guarded = [];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/EducationController.php
<?php

namespace App\Http\Controllers;
use App\Http\Requests\StoreEducationRequest;
use App\Http\Requests\UpdateEducationRequest;
use App\Models\Education;
use Illuminate\Http\Request;

class EducationController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $educations = auth()->user()->education()->get();
        return view('frontend.education.index', compact('educations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('frontend.education.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreResearchSupervisionRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreEducationRequest $request)
    {
        Education::create([
            'user_id' => auth()->user()->id,
            'degree' => $request->degree,
            'group' => $request->group, 
            'institute' => $request->institute,
            'country' => $request->country,
            'passing_year' => $request->passing_year,
            
        ]);
        return redirect()->route('user.profile.index')->withMessage('Education created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\ResearchSupervision  $researchSupervision
     * @return \Illuminate\Http\Response
     */
    public function show(Education $education)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\ResearchSupervision  $researchSupervision
     * @return \Illuminate\Http\Response
     */
    public function edit(Education $education)
    {
        return view('frontend.education.edit', compact('education'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateResearchSupervisionRequest  $request
     * @param  \App\Models\ResearchSupervision  $researchSupervision
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateEducationRequest $request, Education $education)
    {
        $education->update([
            'degree' => $request->degree,
            'group' => $request->group, 
            'institute' => $request->institute,
            'country' => $request->country,
            'passing_year' => $request->passing_year,
            
        ]);
        return redirect()->route('user.profile.index')->withMessage('Education updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\ResearchSupervision  $researchSupervision
     * @return \Illuminate\Http\Response
     */
    public function destroy(Education $education)
    {
        $education->delete();
        return redirect()->route('user.profile.index')->withMessage('Education deleted successfully');
    }
}

resources/views/frontend/education/create.blade.php
<x-frontend.layout.master>
    <x-slot name="title">Add Education</x-slot>

    <main id="main my-5 py-5">

        <div class="card my-5 mb-4">
            <div class="mx-auto card w-75 rounded mb-5 mt-5">
                <x-frontend.form.card_header text="Add new Education " class="rounded bg-white py-2" />
                <hr>
                <div class="card-body">
                    <form class="row g-3" role="form" action="{{ route('educations.store') }}" method="post">
                        @csrf
                        <x-backend.alertmessage.alertmessage type="success" />
                        <x-frontend.form.input name="degree" text="Degree" type="text"
                            :value="old('degree')" />
                        <x-frontend.form.input name="group" text="Group/Major Subject" type="text" :value="old('group')" />
                        <x-frontend.form.input name="institute" text="Board/Institute" type="text"
                            :value="old('institute')" />
                        <x-frontend.form.input name="country" text="Country" type="text" :value="old('country')" />
                        <x-frontend.form.input name="passing_year" text="Passing year" type="text"
                            :value="old('passing_year')" />
                        

                        {{-- <div class="form-check">
                            <input name="is_active" class="form-check-input" type="checkbox" value="1"
                                id="isActiveInput" checked>
                            <label class="form-check-label" for="isActiveInput">
                                Is Active
                            </label>
                        </div> --}}
                        <div class="card-footer bg-white">
                            <div class="d-grid gap-2 col-6 mx-auto d-flex justify-content-center">
                                <button type="submit" class="btn btn-success btn-block"
                                    type="button"><strong>Submit</strong></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
</x-frontend.layout.master>

resources/views/frontend/education/edit.blade.php
<x-frontend.layout.master>
    <x-slot name="title">Edit Education</x-slot>

    <main id="main my-5 py-5">

        <div class="card my-5 mb-4">
            <div class="mx-auto card w-75 rounded mb-5 mt-5">
                <x-frontend.form.card_header text="Edit Education" class="rounded bg-white py-2" />
                <hr>
                <div class="card-body">
                    <form class="row g-3" role="form" action="{{ route('educations.update', $education->id) }}" method="post">
                        @csrf
                        @method('patch')
                        <x-backend.alertmessage.alertmessage type="success" />
                        <x-frontend.form.input name="degree" text="Degree" type="text"
                            :value="old('degree', $education->degree)" />
                        <x-frontend.form.input name="group" text="Group/Major Subject" type="text" :value="old('group', $education->group)" />
                        <x-frontend.form.input name="institute" text="Board/Institute" type="text" :value="old('institute', $education->institute)" />
                        <x-frontend.form.input name="country" text="Country" type="text" :value="old('country', $education->country)" />
                        <x-frontend.form.input name="passing_year" text="Passing Year" type="text"
                            :value="old('passing_year', $education->passing_year)" />
                       

                        <div class="card-footer bg-white">
                            <div class="d-grid gap-2 col-6 mx-auto d-flex justify-content-center">
                                <button type="submit" class="btn btn-success btn-block"
                                    type="button"><strong>Submit</strong></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
</x-frontend.layout.master>

resources/views/frontend/education/index.blade.php
<x-frontend.layout.master>
    <x-slot name="title">Education</x-slot>

    <main id="main my-5 py-5">

        <div class="card my-5 mb-4">
            <div class="mx-auto card w-75 rounded mb-5 mt-5">
                <x-frontend.form.card_header text="Education" class="rounded bg-white py-2" />
                <h6 class="text-end pe-5"><a class="btn btn-primary" href="{{ route('eduactions.create') }}">Add
                        new</a></h6>
                <hr>
                <div class="card-body">
                    <div class="row">
                        <table class="table table-responsive">
                            <thead>
                                <tr>
                                    <th>Degree</th>
                                    <th>Group/Major Subject</th>
                                    <th>Board/Institute</th>
                                    <th>Country</th>
                                    <th>Passing Year</th>

                                    <th width="200px">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($educations as $edu)
                                <tr>
                                    <td>{{ $edu->degree }}</td>
                                    <td>{{ $edu->group }}</td>
                                    <td>{{ $edu->institute }}</td>
                                    <td>{{ $edu->country }}</td>
                                    <td>{{ $edu->passing_year }}</td>
                                    <td>
                                        <a href="{{ route('educations.edit', $edu->id) }}"
                                            class="btn btn-sm btn-outline-warning">Edit</a>
                                        <form class="d-inline" method="post"
                                            action="{{ route('educations.destroy', $edu->id) }}">
                                            @csrf
                                            @method('delete')
                                            <button class="btn btn-sm btn-outline-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="6" class="text-center">
                                        No Educations information found.
                                    </td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>
</x-frontend.layout.master>