routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LibraryController;
use App\Http\Controllers\CategoryController;
// use App\Http\Controllers\CarouselController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\RequestBookController;
use App\Http\Controllers\ApprovedBookController;
use App\Http\Controllers\IssueBookController;
use App\Http\Controllers\ReturnBookController;
use App\Http\Controllers\ReissueBookController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\ContactUsController;
use App\Http\Controllers\AboutUsController;
use App\Http\Controllers\AwardController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EducationController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\MembershipController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PublicationController;
use App\Http\Controllers\ResearchSupervisionController;
use App\Http\Controllers\TeachingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend/home');
})->name('homepage');

require __DIR__.'/auth.php';
// frontend all route
Route::middleware('auth')->controller(LibraryController::class)->group(function(){
    Route::get('/library-dashboard','index')->name('library-dashboard');
    Route::get('/get-book','booklist')->name('get-book');
    Route::get('/teacher-list','teacherlist')->name('teacher-list');
    Route::get('/teacher-details/{id}','teacherDetails')->name('teacher-details');
    Route::get('/student-list','studentlist')->name('student-list');
    Route::post('/book/request','request_store')->name('book.request');
    Route::get('/request-cancel/{id}/{book_id}','destroy')->name('request.destroy');
    Route::get('/user-reissue/{id}','reissue')->name('user.reissue');
});

Route::middleware('auth')->controller(ContactUsController::class)->group(function(){
  Route::get('/user/contactus','index')->name('user.contactus.index');
  Route::post('/contactus','store')->name('user.contactus.store');
});

Route::controller(AboutUsController::class)->group(function(){
  Route::get('/user/aboutus','index')->name('user.aboutus.index');
});

Route::controller(EventController::class)->group(function(){
  Route::get('/user/event','index')->name('user.event.index');
});

//Teacher Profile Info

Route::middleware('auth')->group(function() {
  Route::middleware(['role:teacher'])->group(function() {
    Route::resource('research-supervisions', ResearchSupervisionController::class);
    Route::resource('teachings', TeachingController::class);
    Route::resource('educations', EducationController::class);
    Route::resource('publications', PublicationController::class);
    Route::resource('awards', AwardController::class);
    Route::resource('memberships', MembershipController::class);
  });

  Route::controller(ProfileController::class)->group(function(){
    Route::get('/user/profile','index')->name('user.profile.index');
    Route::patch('/user/profile','updateProfile')->name('user.profile.update');
    Route::patch('/change/password','changePassword')->name('user.change.password');
  });
});

Route::middleware(['auth', 'role:admin'])->group(function() {
  Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
  
  Route::resource('teachers', TeacherController::class);
  Route::resource('students', StudentController::class);

  Route::resource('categories', CategoryController::class);
  Route::resource('books', BookController::class);
//  Route::resource('carousels', CarouselController::class)->middleware(['auth','role']);
  
  Route::get('/admin-profile',[ProfileController::class, 'adminIndex'])->name('admin.profile.index');
  
  Route::get('/reissuebooks',[ReissueBookController::class, 'index'])->name('reissue.book.index');
  Route::get('/reissuebooks/{id}',[ReissueBookController::class, 'reissue'])->name('reissue.book.reissue');

  Route::get('/returnbooks',[ReturnBookController::class, 'index'])->name('return.book.index');

  Route::get('/issuebooks',[IssueBookController::class, 'index'])->name('issue.book.index');
  Route::get('/issuebooks/{id}/{book_id}',[IssueBookController::class, 'return'])->name('issue.book.return');

  Route::get('/approvedbooks',[ApprovedBookController::class, 'index'])->name('approved.book.index');
  Route::get('/approvedbooks/{id}',[ApprovedBookController::class, 'issue'])->name('approved.book.issue');

  Route::get('/requestbooks',[RequestBookController::class, 'index'])->name('request.book.index');
  Route::get('/requestbooks/{id}/{book_id}',[RequestBookController::class, 'approved'])->name('request.book.approved');

});
//end manage book library request and status change of admin

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
        'status',
        'v_code',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function profile()
    {
        return $this->hasOne(Profile::class);
    }



    public function requestbook()
    {
        return $this->hasMany(BookRequest::class);
    }

    public function researchSupervisions()
    {
        return $this->hasMany(ResearchSupervision::class);
    }
    public function Teaching()
    {
        return $this->hasMany(Teaching::class);
    }
    public function education()
    {
        return $this->hasMany(Education::class);
    }
    public function Publication()
    {
        return $this->hasMany(Publication::class);
    }
    public function Award()
    {
        return $this->hasMany(Award::class);
    }
    public function Membership()
    {
        return $this->hasMany(Membership::class);
    }
}

resources/views/admin/user/edit.blade.php
<x-backend.layout.master title="user" bottomheader="Update user">

  <x-backend.alertmessage.alertmessage />
  
    <div class="container card w-50 ">
        <form class="form-horizontal" role="form" action="{{ route('users.update',['user'=>$useredit->id]) }}" method="post" enctype="multipart/form-data">
           @csrf
           @method('patch')
            <div class="card-header bg-info"> <h2 class="text-center mt-2"></h2>User</div>
            <br>
           <x-backend.alertmessage.alertmessage type="success"/>
            <br>
            <br>
            <x-frontend.form.input name="name" text="User" type="text" :value="old('name', $useredit->name)" />
            <x-frontend.form.input name="email" text="Email" type="email" :value="old('email', $useredit->email)" />
              <x-frontend.form.input name="role_id" text="role_id" type="text" :value="old('user_role', $useredit->role_id)" />
    
          <button type="submit" class="btn btn-success d-flex">Update</button>
               
      
      
      
      
      
            </div> 
            
                
        
        </form>   
       
      </div>
         



 

</x-backend.layout.master>

resources/views/admin/user/show.blade.php
 
    <x-backend.layout.master>
        @slot('title')
        User Details
        @endslot
    <div class="card mb-4">
        @slot('bottomheader')
      User Details
        @endslot
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
           Usert Details
           <a href="{{ route('sellbooks.index') }}"> <button class="btn btn-sm btn-info">ADD BOOK</button></a>
        </div>
      
        <div class="card w-50 mx-auto mt-4">
            <div class="card-header text-center">
              <b> User Details</b>
            </div>
            <address class="m-5">
              User Name :{{ $usershow->name }} <br>
              User Email: {{ $usershow->email }} <br>
             
            </address>
          </div>
    </div>
     
    </x-backend.layout.master>
 
 
 

resources/views/admin/user/student.blade.php
<x-backend.layout.master>

      @slot('title')
    teacher
    @endslot
 <main id="main" class="main">

    <div class="pagetitle">
      <h1>Teacher List</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
          <li class="breadcrumb-item active">TeacherList</li>
        </ol>
      <a href="{{ route('register') }}" class="btn btn-primary btn-sm">Add Teacher</a>
      </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
         <x-backend.alertmessage.alertmessage type="success"/>
<table class="table table-bordered border-primary">
   <thead>
                <tr>
                    <th>SL No</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Book Edition</th>
                    <th>Book Quantity</th>
                    <th>Category</th>
                    <th>Image</th>
                    <th>Status</th>
                    <th>Created Data</th>
                    <th>Action</th>
                </tr>
            </thead>
             <tbody>
                @foreach ($books as $book)
                    
               
               <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $book->booktitle }}</td>
                    <td>{{ $book->bookauthor }}</td>
                    <td>{{ $book->bookedition }}</td>
                    <td>{{ $book->bookquantity }}</td>
                    <td>{{ $book->categories->title }}</td>
                    <td class="text-center"><img src="{{ asset('storage/books').'/'.$book->bookimage }}" alt="hhh" class="img-fluid" style="width:100px;height:100px"></td>
                    <td>{{ $book->status?'Active':'In Active' }}</td>
                    <td>{{ $book->created_at }}</td>
                     
                    

                    
                    <td>
                        <div class="d-flex ">
                            <x-backend.buttonlink.viewlink  action="{{ route('books.show',['book'=>$book->id ])}}"/>
                            <x-backend.buttonlink.editlink action="{{ route('books.edit',['book'=>$book->id ])}}"/>
                            <x-backend.buttonlink.deletelink action="{{ route('books.destroy',['book'=>$book->id ])}}"/>
                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
</table>



      
       
    </section>

  </main><!-- End #main -->







 
<div class="modal fade" id="BookModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header bg-primary text-white center">
           Add New Book
          <button type="button" class="btn-close btn-white" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
             <form class="row g-3" role="form" action="{{ route('books.store') }}" method="post" enctype="multipart/form-data">
                @csrf
              
                 
                 <br>
                

                 <x-backend.alertmessage.alertmessage type="success"/> 
                
                <select name="category" id="" class="form-select" aria-label="Default select example">
                    <option value="">Select Chategory</option>
                    @foreach ($categories as $category)
                    <option value="{{ $category->id }}">{{ $category->title }}</option>
                    @endforeach
                </select>
               
                <div class="col-md-6">
                    <x-frontend.form.input name="booktitle" text="Book Tile" type="text" :value="old('booktitle')" />
               </div>
                <div class="col-md-6">
                    <x-frontend.form.input name="bookauthor" text="Book Author" type="text" :value="old('bookauthor')" />
               </div>
                <div class="col-md-6">
                    <x-frontend.form.input name="bookedition" text="Book Edition" type="text" :value="old('bookedition')" />
               </div>
                <div class="col-md-6">
                    <x-frontend.form.input name="bookquantity" text="Book Quantity" type="number" :value="old('bookquantity')" />
               </div>
              
                
                  <div class="col-md-12">
                    <x-frontend.form.input name="bookimage" text="Book Image" type="file"/>
                  </div>
                  
               <div class="form-check">
                <input name="is_active" class="form-check-input" type="checkbox" value="1" id="isActiveInput" checked>
                <label class="form-check-label" for="isActiveInput">
                    Is Active
                </label>
            </div>
                
    
                  
             <div class="card-footer bg-white">
                <div class="d-grid gap-2 col-6 mx-auto d-flex">
                    <button type="submit" class="btn btn-success w-50 btn-sm" type="button">Save <i class="fa-solid fa-paper-plane"></i></button>
                     <a href="{{ route('books.index') }}"><button class="btn btn-danger btn-sm" type="button">Cancel</button></a>
                  </div>
          </div> 
        </form> 
      </div>
    </div>
  </div>
  <script>
    $.ajaxSetup({
    headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
});
  </script>
  <script>
    $(document).ready(function(){
        $(document).on('click','.add_category',function(e){
            e.preventDefualt();
            let title=$('#title').val();
            let description=$('#description').val();
            console.log(title+description);
        })
    })
  </script>
</x-backend.layout.master>

resources/views/admin/user/userlist.blade.php
<x-backend.layout.master>
    @slot('title')
     User List
    @endslot
<div class="card mb-4">
<div class="card-header " style="background-color: #defffe">
        <i class="fas fa-table me-1"></i>
        UserList
        <a href="{{ route('user.register') }}"> <button class="btn btn-outline-info btn-sm text-black">Add New User</button></a>

    </div>
   
   <x-backend.alertmessage.alertmessage type="success"/>
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>SL No</th>
                    <th>Name</th>
                    <th>Role</th>
                    <th>Email</th>
                    <th>Created_at</th>
                    <th>Updated_at</th>
                    <th>Action</th>
                     
                </tr>
            </thead>
           
            <tbody>
                @foreach ($users as $user)
                    
               
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->roles->role}}</td>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->created_at }}</td>
                    <td>{{ $user->updated_at }}</td>
                     
                     <td>
                        <div class="d-flex">
                        <x-backend.buttonlink.viewlink action="{{ route('users.show',['user'=>$user->id ])}}"/>
                        <x-backend.buttonlink.editlink action="{{ route('users.edit',['user'=>$user->id ])}}"/>
               
                        <x-backend.buttonlink.deletelink action="{{ route('users.destroy',['user'=>$user->id ])}}"/>
                        </div>
                    </td>
                         {{-- <a href="{{ route('sellbook.show',[
                            'sellbook'=>$sellbooklist->id
                         ]) }}">
                            <i class="fa-solid fa-pencil text-success"style="margin-left:20px"></i>
                        </a> --}}
                     {{-- <form action="{{ route('sellbook.destroy',['sellbook'=>$sellbooklist->id] )}}" method="POST">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn text-danger d-inline" onclick="confirm('Are you Sure?')"><i class="fa-solid fa-trash-can"></i></button>
                       

                     </form> --}}
                        

                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
 
</x-backend.layout.master>